Repository stonier/ecl_core, pull requests merged in 2020-01, with the labels that each got.

#94 Fix compilation of ecl_threads
  ecl_threads/src/lib/mutex_pos.cpp
Labels: type: bug

#95 [infra] no system includes
  ecl_concepts/CMakeLists.txt
  ecl_containers/CMakeLists.txt
  ecl_converters/CMakeLists.txt
  ecl_core_apps/CMakeLists.txt
  ecl_devices/.cproject
  ecl_devices/CMakeLists.txt
  ecl_exceptions/CMakeLists.txt
  ecl_filesystem/CMakeLists.txt
  ecl_formatters/CMakeLists.txt
  ecl_geometry/CMakeLists.txt
  ecl_ipc/CMakeLists.txt
  ecl_linear_algebra/CMakeLists.txt
  ecl_manipulators/CMakeLists.txt
  ecl_math/CMakeLists.txt
  ecl_mobile_robot/CMakeLists.txt
  ecl_mpl/CMakeLists.txt
  ecl_sigslots/CMakeLists.txt
  ecl_statistics/CMakeLists.txt
  ecl_streams/CMakeLists.txt
  ecl_threads/CMakeLists.txt
  ecl_time/CMakeLists.txt
  ecl_type_traits/CMakeLists.txt
  ecl_utilities/CMakeLists.txt
Labels: type: infra

#96 [exceptions] bugfix dangling pointers on what const char* returns
  ecl_exceptions/CHANGELOG.rst
  ecl_exceptions/include/ecl/exceptions/data_exception.hpp
  ecl_exceptions/include/ecl/exceptions/standard_exception.hpp
  ecl_exceptions/src/lib/standard_exception.cpp
Labels: type: bug

#99 [concepts/streams] fix two warnings as error problems
  ecl_concepts/include/ecl/concepts/nullary_function.hpp
  ecl_streams/include/ecl/streams/socket_streams.hpp
Labels: type: bug

#100 [infra] fix a bunch of problems pointed out by clang static analysis.
  ecl_converters/include/ecl/converters/char_strings.hpp
  ecl_core_apps/src/benchmarks/flops.cpp
  ecl_core_apps/src/benchmarks/string_conversions.cpp
  ecl_devices/src/lib/shared_file.cpp
  ecl_formatters/include/ecl/formatters/floats.hpp
  ecl_geometry/src/test/angles.cpp
  ecl_statistics/include/ecl/statistics/cumulative_statistics.hpp
  ecl_type_traits/src/test/numeric_limits.cpp
Labels: type: enhancement
